name: GitHub Actions Demo
on: [push]
jobs:
  testbox:
    runs-on: ubuntu-latest
    container:
      image: centos:7
    steps:  
    - name: Checkout Project
      uses: actions/checkout@v1
      submodule: true
    - name: What OS is running
      run: uname -a

